### ISSUE TITLE
Quiz Bot For Whatsapp And Telegram Using Dialog flow And Spreadsheet 

### ISSUE THREAD

**Issue by ajaydeshmane** [adsau59/Supbot2#2]
As You Know I have Commented On Your YouTube Channel To Make A Quiz Chat Bot For Whats app and Telegram Using Dialogflow And Spredsheet Make Sure You DO all Project and connected with dataa base wich shows Points all over users and self point 

also do a tutorial For it So People Can Learn Through You Hope You Do this 

Best Luck For You And Your Channel 

Thanks

**Comment by adam-saudagar** [comment]
please comment on youtube for video requests, this thread is only for bugs or feature requests
